url: "https://mathephor-ceji.github.io"
baseurl: ""

title: "Ce Ji"
title_zh: "季策"
description: "Academic homepage of Ce Ji, a mathematician working in mathematical physics, algebraic geometry, and integrable systems."

lang: en
timezone: Asia/Shanghai
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - MAINTAIN.md
  - README.md
  - vendor
