remote_theme: yaoyao-liu/minimal-light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ce Ji
description: in Mathematical Physics
show_downloads: false
google_analytics:
